# Generated by Django 5.1.15 on 2026-03-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogSincronizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "proveedor",
                    models.CharField(max_length=100, verbose_name="Proveedor"),
                ),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("equipos", "Equipos"),
                            ("partidos", "Partidos"),
                            ("resultados", "Resultados"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de entidad",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_progreso", "En progreso"),
                            ("exitoso", "Exitoso"),
                            ("fallo_parcial", "Fallo parcial"),
                            ("fallido", "Fallido"),
                        ],
                        default="en_progreso",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "registros_procesados",
                    models.IntegerField(default=0, verbose_name="Registros procesados"),
                ),
                (
                    "detalle_error",
                    models.TextField(blank=True, verbose_name="Detalle de error"),
                ),
                (
                    "inicio",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inicio"),
                ),
                (
                    "fin",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
            ],
            options={
                "verbose_name": "Log de sincronización",
                "verbose_name_plural": "Logs de sincronización",
                "ordering": ["-created_at"],
            },
        ),
    ]
