# Generated by Django 5.1.15 on 2026-03-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaPuntaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("resultado_exacto", "Resultado exacto"),
                            ("acierto_ganador", "Acertar ganador/empate"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de regla",
                    ),
                ),
                ("puntos", models.IntegerField(verbose_name="Puntos")),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descripción"
                    ),
                ),
                (
                    "torneo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglas_puntaje",
                        to="tournaments.torneo",
                        verbose_name="Torneo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de puntaje",
                "verbose_name_plural": "Reglas de puntaje",
                "unique_together": {("torneo", "tipo")},
            },
        ),
    ]
