# Generated by Django 5.1.15 on 2026-03-23 21:47

import apps.spaces.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        default=apps.spaces.models.generar_codigo,
                        max_length=20,
                        unique=True,
                        verbose_name="Código de invitación",
                    ),
                ),
                (
                    "es_publica",
                    models.BooleanField(default=False, verbose_name="Es pública"),
                ),
                (
                    "max_miembros",
                    models.PositiveIntegerField(
                        default=100, verbose_name="Máx. miembros"
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sala",
                "verbose_name_plural": "Salas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MiembroSala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("admin", "Administrador"), ("miembro", "Miembro")],
                        default="miembro",
                        max_length=10,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="spaces.sala",
                        verbose_name="Sala",
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro de sala",
                "verbose_name_plural": "Miembros de sala",
                "unique_together": {("sala", "usuario")},
            },
        ),
    ]
