# Generated by Django 5.1.15 on 2026-03-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "fecha_hora",
                    models.DateTimeField(db_index=True, verbose_name="Fecha y hora"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_juego", "En juego"),
                            ("finalizado", "Finalizado"),
                            ("suspendido", "Suspendido"),
                            ("cancelado", "Cancelado"),
                            ("postergado", "Postergado"),
                        ],
                        db_index=True,
                        default="programado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "goles_local",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Goles local"
                    ),
                ),
                (
                    "goles_visitante",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Goles visitante"
                    ),
                ),
                (
                    "api_externa_id",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="ID en API externa",
                    ),
                ),
                (
                    "equipo_local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_local",
                        to="tournaments.equipo",
                        verbose_name="Equipo local",
                    ),
                ),
                (
                    "equipo_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos_visitante",
                        to="tournaments.equipo",
                        verbose_name="Equipo visitante",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos",
                        to="tournaments.fase",
                        verbose_name="Fase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partido",
                "verbose_name_plural": "Partidos",
                "ordering": ["fecha_hora"],
                "indexes": [
                    models.Index(
                        fields=["fecha_hora", "estado"], name="idx_fecha_estado"
                    )
                ],
            },
        ),
    ]
